services:
  postgres:
    image: postgres:16-alpine
    container_name: lumiere-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-lumiere}
      POSTGRES_PASSWORD: ${DB_PASS:-lumiere123}
      POSTGRES_DB: ${DB_NAME:-lumiere}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/migrations.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    container_name: lumiere-torrserver
    restart: unless-stopped
    ports:
      - "${TORRSERVER_PORT:-8590}:8590"
    environment:
      - TS_PORT=8590
      - TS_DONTKILL=1
    volumes:
      - torrserver-data:/opt/torrserver/db

volumes:
  pgdata:
  torrserver-data:
