version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lumiere-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-lumiere}
      POSTGRES_PASSWORD: ${DB_PASS:-lumiere123}
      POSTGRES_DB: ${DB_NAME:-lumiere}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
